bigdata/urls.py
from django.urls import path

from . import views

app_name = 'bigdata'
urlpatterns = [
    path('',                            views.index,   name='index'),
    path('<int:user_id>/',              views.detail,  name='detail'),
    #path('<int:question_id>/',         views.detail,  name='detail'),
    #path('<int:question_id>/results/', views.results, name='results'),
    #path('<int:question_id>/vote/',    views.vote,    name='vote'),
]

publisher/urls.py
from django.urls import path

from .views import index,detail,fillblank,multiplechoice,statistics
from .views import get_name, create_fb_problem, create_mc_problem, vote
from .views import ProbList, signup
from django.contrib.auth.views import LoginView,LogoutView

app_name="publisher"
urlpatterns = [
	path("",					index,				name="index"),
	path("<int:pk>",			detail,				name="detail"),
	path("<int:prob_id>/fb",	fillblank,			name="fillblank"),
	path("<int:prob_id>/mc",	multiplechoice,		name="multiplechoice"),
	path("<int:prob_id>/statistics", statistics,	name="statistics"),
	path("name",                get_name,			name="name"),
	path("fb_create",			create_fb_problem,  name="create_fb_problem"),
	path("mc_create",			create_mc_problem,  name="create_mc_problem"),
	path("vote/<int:prob_id>",	vote,				name="vote"),
	path("rest",			    ProbList.as_view(), name="rest"),
	path('signup',				signup,             name="signup"),
	path('login',				LoginView.as_view(template_name="publisher/login.html"),   name="login"),
	path('logout',				LogoutView.as_view(template_name="publisher/logout.html"), name="logout"),

]

publisher/forms.py
from django import forms
from .models import Choice, FillInBlankProblem, MultipleChoiceProblem, Problem
from django.forms import inlineformset_factory
from django.forms import BaseInlineFormSet
from django.core.exceptions import ValidationError

from django.contrib.auth.forms  import UserCreationForm
from django.contrib.auth.models import User

class NameForm(forms.Form):
	your_name = forms.CharField(label="Your name", max_length=50)

class FillInBlankProblemModelForm(forms.ModelForm):
	class Meta:
		model  = FillInBlankProblem
		widgets = {
					'text':		forms.Textarea(attrs={'rows':3, 'cols':60}),
					'lecture':	forms.Textarea(attrs={'rows':3, 'cols':60}),
					'headline':	forms.TextInput(attrs={'size':40}),
					'hint':		forms.TextInput(attrs={'size':40}),
					'answer':	forms.TextInput(attrs={'size':40}),
					'appendix': forms.TextInput(attrs={'size':40}),
					'subjects': forms.SelectMultiple(attrs={'size':8, 'style': 'min-width:60px;'}),
				  }
		fields  = ('subjects', 'level',    'headline', 'text', 
				   'answer',   'appendix', 'answer_type', 'hint',    'lecture')
		#exclude = ('prob_type', 'num_correct', 'num_wrong', 'num_likes', 'num_dislikes')

class MultipleChoiceProblemModelForm(forms.ModelForm):
	class Meta:
		model = MultipleChoiceProblem
		widgets = {
					'text':		forms.Textarea(attrs={'rows':3, 'cols':60}),
					'lecture':	forms.Textarea(attrs={'rows':3, 'cols':60}),
					'headline':	forms.TextInput(attrs={'size':40}),
					'hint':		forms.TextInput(attrs={'size':40}),
					'subjects': forms.SelectMultiple(attrs={'size':8, 'style': 'min-width:60px;'}),
					'prob_type': forms.HiddenInput()
				  }
		fields  = ('subjects', 'level',    'headline', 'text', 
				    'hint',    'lecture',  'prob_type')

class MCInlineFormSet(BaseInlineFormSet):
	def clean(self):
		super().clean()
		count  = 0
		nforms = 0
		for form in self.forms:
			for key in form.cleaned_data.keys():
				if "correct" in key:
					count += form.cleaned_data.get(key, 0)
				if "choice_text" in key:
					if form.cleaned_data[key]:
						nforms += 1
		if nforms < 2 or nforms > 5:
			raise ValidationError("Please provide minum 2, maximum 5 chocies!") 
		if count != 1:
			raise ValidationError("Please mark one and only one answer as correct!")
			

class ChoiceModelForm(forms.ModelForm):
	class Meta:
		model   = Choice
		fields  = ('correct', 'choice_text')			
		widgets = {'choice_text': forms.TextInput(attrs={'size':40})}

ChoiceModelFormSet=inlineformset_factory(MultipleChoiceProblem, Choice,
						form = ChoiceModelForm, 
						max_num=5, extra=5,
						formset = MCInlineFormSet,
						can_delete=False
					)


class SignUpForm(UserCreationForm):
	first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
	last_name  = forms.CharField(max_length=30, required=False, help_text='Optional.')
	email      = forms.EmailField(max_length=254, help_text='Required. Valid')
	
	class Meta:
		model  = User
		fields = ('first_name', 'last_name', 'email', 'username', 'password1','password2')

publisher/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required

# Create your views here.

from .models import Choice,Problem,MultipleChoiceProblem,FillInBlankProblem
from .forms  import NameForm,FillInBlankProblemModelForm,MultipleChoiceProblemModelForm
from .forms  import ChoiceModelFormSet
from .forms  import SignUpForm

from rest_framework.views    import APIView
from rest_framework.response import Response
from .serializers import ProblemSerializer 

def index(request):
	problems = Problem.objects.all().order_by("-date_created")[:20]
	headers  = [problem.index_header() for problem in problems]
	context  = {"headers":headers}
	return render(request, "publisher/index.html", context)

def detail(request, pk):
	try:
		prob = Problem.objects.get(pk=pk)
		if prob.prob_type == "填空":
			child     = FillInBlankProblem.objects.get(pk=pk)
			prob_type = "fillblank"
			choices   = None
		elif prob.prob_type == "选择":
			child     = MultipleChoiceProblem.objects.get(pk=pk)
			prob_type = "choice"
			choices   = Choice.objects.filter(problem=pk) 
		else:
			child	  = None
			prob_type = None
			choices   = None
	except:
		child     = None
		prob_type = None
		choices   = None
	context = {"child":child, "problem_type":prob_type, "choices":choices}
	return render(request, "publisher/detail.html", context)

def multiplechoice(request, prob_id):
	problem = get_object_or_404(MultipleChoiceProblem, pk=prob_id)
	user_choice_id = request.POST.get('mc-prob-id-'+str(prob_id), 0)
	if user_choice_id:
		choice  = get_object_or_404(Choice, pk=user_choice_id)
		choice.votes += 1
		choice.save()
		if choice.correct:
			problem.num_correct += 1
			problem.save()
			context = {'problem':problem, 'flag':True,  'user_choice_id':int(user_choice_id)}
		else:
			problem.num_wrong += 1
			problem.save()
			context = {'problem':problem, 'flag':False, 'user_choice_id':int(user_choice_id)}
		return render(request, "publisher/answer_mc.html", context)
	else:
		return HttpResponseRedirect(reverse("publisher:detail", args=(prob_id,)))

def fillblank(request, prob_id):
	problem   = get_object_or_404(FillInBlankProblem, pk=prob_id)	
	userinput = request.POST.get('fb-prob-id-'+str(prob_id), None)
	if userinput:
		if problem.answer == userinput:
			problem.num_correct += 1
			problem.save()
			context = {'problem':problem, 'flag':True}
		else:
			problem.num_wrong   += 1
			problem.save()
			context = {'problem':problem, 'flag':False, 'userinput':userinput}
		return render(request, "publisher/answer_fb.html", context)
	else:
		return HttpResponseRedirect(reverse("publisher:detail", args=(prob_id,)))

def statistics(request, prob_id):
	problem = get_object_or_404(Problem, pk=prob_id)
	if problem.prob_type == "选择":
		problem = get_object_or_404(MultipleChoiceProblem, pk=prob_id)
	else:
		problem = get_object_or_404(FillInBlankProblem, pk=prob_id)
	context = {'problem':problem}
	return render(request, "publisher/statistics.html", context)

def get_name(request):
	if request.method == "POST":
		form = NameForm(request.POST)
		if form.is_valid():
			return HttpResponse("hello %s" % form.cleaned_data['your_name'] )
	else:
		form = NameForm()
	context = {'form':form}
	return render(request, 'publisher/name.html', context)

@login_required(login_url="publisher:login")
def create_fb_problem(request):
	if request.method == "POST":
		form = FillInBlankProblemModelForm(request.POST)
		if form.is_valid():
			prob = form.save(commit=False)
			if request.user.is_authenticated:
				prob.author = request.user
			prob.save()
			form.save_m2m()
			return HttpResponseRedirect(reverse("publisher:detail", args=(prob.id,)))
	else:
		form = FillInBlankProblemModelForm()
	context = {"form":form}
	return render(request, "publisher/create_fb_problem.html", context)

def create_mc_problem0(request):
	if request.method == "POST":
		form = MultipleChoiceProblemModelForm(request.POST)
		if form.is_valid():
			prob = form.save()
			return HttpResponseRedirect(reverse("publisher:detail", args=(prob.id,)))
	else:
		form = MultipleChoiceProblemModelForm()
	context = {'form':form}
	return render(request, "publisher/create_mc_problem.html", context) 


@login_required(login_url="publisher:login")
def create_mc_problem(request):
	if request.method == "POST":
		form = MultipleChoiceProblemModelForm(request.POST)
		if form.is_valid():
			prob = form.save(commit=False)
			if request.user.is_authenticated:
				prob.author = request.user
			prob.save()
			form.save_m2m()
			formset = ChoiceModelFormSet(request.POST, instance=prob)
			if formset.is_valid():
				formset.save()
				return HttpResponseRedirect(reverse("publisher:detail", args=(prob.id,)))
			else:
				prob.delete()
		else:
			formset = ChoiceModelFormSet(request.POST)
	else:
		form = MultipleChoiceProblemModelForm(initial={'prob_type':Problem.TYPE.选择})
		prob = MultipleChoiceProblem()
		formset = ChoiceModelFormSet(instance=prob)
	context = {'form':form, 'formset':formset}
	return render(request, "publisher/create_mc_problem.html", context) 

def vote(request, prob_id):
	problem  = get_object_or_404(Problem, pk=prob_id)
	if request.method == "POST":
		likeQ = request.POST.get('vote', 0)
		if likeQ == 0:		#user submitted form, but did not really vote	
			return HttpResponseRedirect(reverse("publisher:statistics", args=(prob_id,)))
		elif likeQ == "pos":
			problem.num_likes += 1
		elif likeQ == "neg":
			problem.num_dislikes += 1
		problem.save()
		return HttpResponseRedirect(reverse("publisher:index"))
	else:
		return HttpResponseRedirect(reverse("publisher:statistics", args=(prob_id,)))

class ProbList(APIView):

	def get(self, request):
		problems   = Problem.objects.all().order_by('-date_created')[:20]
		serializer = ProblemSerializer(problems, many=True)
		return Response(serializer.data)

def signup(request):
	if request.method == "POST":
		form = SignUpForm(request.POST)
		if form.is_valid():
			form.save()
			username     = form.cleaned_data.get('username')
			raw_password = form.cleaned_data.get('password1')
			user = authenticate(username=username, password=raw_password)			
			login(request, user)
			return redirect('publisher:index')	
	else:
		form = SignUpForm()	
	return render(request, "publisher/signup.html", {'form':form})

publisher/templates/publisher/answer_fb.html
{% extends "publisher/base.html" %}

{% block main %}
<h3>Topic. {{problem.headline}}</h3>
<hr/>
<p><b>Question.</b> {{problem.text}} </p>
<hr/>
<label>Comments: </label>
{% if flag %}
	<p> Good job! </p>
{% else %}
	<p> Oops! your input "{{userinput}}" is wrong. The correct answer is "{{problem.answer}}".</p>
	{% if problem.solution %}
        <h4>Detailed explanation:</h4>
        {{problem.solution}}
    {% else %}
        <p>Sorry! The author did not provide a detailed solution！</p>
    {% endif %}
{% endif %}
<hr>
<p><label>Big Data:</label> <a href="{% url 'publisher:statistics' problem.id %}">view statistics</a></p>

<hr>
&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'publisher:index' %}">home</a>

{% endblock %}

publisher/templates/publisher/answer_mc.html
{% extends "publisher/base.html" %}

{% block main %}
<h3>Topic. {{problem.headline}}</h3>
<hr/>
<p><b>Question.</b> {{problem.text}} </p>

{% for choice in problem.choice_set.all %}
	({{forloop.counter}}).&nbsp;
	{% if choice.correct %}
		<span style="background-color:green;color:white;"> {{choice.choice_text}} </span> <br/>  
	{% else %}
		{% if choice.id == user_choice_id %}
			<span style="background-color:red;color:white;"> {{choice.choice_text}} </span> &nbsp;&nbsp;&#x274C;<br/>
		{% else %}
			{{choice.choice_text}} <br/>
		{% endif %}
	{% endif %}
{% endfor %}
<hr/>
<label>Comments: </label>
{% if flag %}
	<p> Good job！</p>
{% else %}
	<p> Oops！You missed it!</p>
	{% if problem.solution %}
		<h4>Detailed explanation:</h4>
		{{problem.solution}}
	{% else %}
		<p>Sorry! The author did not provide a detailed solution！</p>
	{% endif %}
{% endif %}
<hr>
<p><label>Big Data:</label> <a href="{% url 'publisher:statistics' problem.id %}">view statistics</a></p>

<hr>
&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'publisher:index' %}">home</a>

{% endblock %}

publisher/templates/publisher/base.html
{% load static %}
<html>
<head>
	<link rel="stylesheet" type="text/css" href="{% static 'publisher/style.css' %}">
	<title> {% block title %} langya forum {% endblock %}</title>
</head>
<body>
<header>
<p align="center"> Langya Forum </p>
<p align="right"> 
{%if not user.is_authenticated%}
	<a style="color:white;" href="{% url 'publisher:login' %}">login</a> | 
	<a style="color:white;" href="{% url 'publisher:signup' %}">signup</a> 
{%else%}
 User:&nbsp;&nbsp;{{user.username}}&nbsp;&nbsp;<a style="color:white;" href="{% url 'publisher:logout' %}">logout</a> 
{%endif%}
<br/>
<a style="color:white;" href="http://math.langya.cloud">langya math for kids</a> </p>
</header>

<div style="margin:0 auto; min-width:600px; max-width:900px;">
	
	{% block main %}
	{% endblock %}	
</div>
	<br/>
	<br/>
<!--
<footer id="footer">
<span style="align:center">Copyright math.langya.cloud </span> |
<span style="align:right">Contact bchencommercial@gmail.com </span>
</footer>
-->
</body>
</html>

publisher/templates/publisher/create_fb_problem.html
{% extends 'publisher/base.html' %}

{%block main %}
<h3>Create a fill-in-blank problem</h3>
<form action="{% url 'publisher:create_fb_problem' %}" method="post">
	{% csrf_token %}
	<p>(neither hint or lecture is mandatory, but please provide them when the problem is difficult)</p>
	<hr/>
	<table style="border:0px">	
	{{ form }}
	<tr><td colspan="2" align="center"> <input type="submit" value="Submit"></td> </tr>
	</table>
</form>
<hr>
    &nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'publisher:index' %}">home</a>

{%endblock%}

publisher/templates/publisher/create_mc_problem.html
{% extends 'publisher/base.html' %}

{%block main %}
<h3>Create a multiple-choice problem</h3>
<form action="{% url 'publisher:create_mc_problem' %}" method="post">
	{% csrf_token %}
	<p>Part A: the problem<br/>
	(neither hint or lecture is mandatory, but please provide them when the problem is difficult)</p>
	<hr/>
	<table style="border:0px">	
	{{ formset.non_form_errors }}
	{{form}} <br/>
	{{ formset.management_form }}
	</table>
	<hr/>
	<p>Part B: the choices (do not forget to check the correct answer)</p>
	<table>
    {% for form in formset %}
		{%if forloop.first %}
		<tr> 
			{%for field in form.visible_fields %}
				<th> {{field.label|capfirst}} </th>
			{%endfor%}
		</tr>
		{%endif%}
		<tr>
        {% for field in form.visible_fields %}
			<td align="center">
				{%if forloop.first%}
					{%for hidden in form.hidden_fields %}
						{{hidden}}
					{%endfor%}
				{%endif%}
				{{ field.errors.as_ul }} {{ field }} 
			</td> 
        {% endfor %}
		</tr>
    {% endfor %}
	<tr><td colspan="2" align="center"> <input type="submit" value="Submit"></td> </tr>
	</table>
</form>
<hr>
&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'publisher:index' %}">home</a>

{%endblock%}

publisher/templates/publisher/create_mc_problem0.html
{% extends 'publisher/base.html' %}

{%block main %}

<form action="{% url 'publisher:create_mc_problem' %}" method="post">

	{% csrf_token %}
	<table style="border:0px">	
	{{ form }}
	<tr><td colspan="2" align="center"> <input type="submit" value="Submit"></td> </tr>
	</table>
</form>

{%endblock%}

publisher/templates/publisher/detail.html
{% extends "publisher/base.html" %}

{% block main %}
{% if child %}
	<h3>Topic. {{ child.headline }} </h3>
	<p><b>Question.</b>  {{ child.text }} </p>
	{% if child.hint %} 
	<p>(hint: {{ child.hint }}) </p>
	{% endif %}
	{% if problem_type == "fillblank" %}	
		<form action="{% url 'publisher:fillblank' child.id %}" method="POST">
		<p>  
			<b>Answer:</b>&nbsp;&nbsp;<input type="text" name="fb-prob-id-{{child.id}}" width="200px;" height="25px;"/> {{ child.appendix }}
		</p>
	{% else  %}
		<hr>
		<form action="{% url 'publisher:multiplechoice' child.id %}" method="POST">
		{% if choices %}
			{% for choice in choices %}
				&nbsp;&nbsp;&nbsp;&nbsp; <input type="radio" name="mc-prob-id-{{child.id}}" id="choice-{{forloop.counter}}" value="{{choice.id}}" > 
				<label style="min-width:80px; font-size:28px;" for="choice-{{forloop.counter}}"> {{choice.choice_text}} </label> </br></br>
			{% endfor %}
		{% endif %}
	{% endif %}	
	<br/><input type="submit" name="submit" value="submit">
		{% csrf_token %}
	</form>
{% else %}
	<p>Sorry! The post you selected does not exist!</p>
{% endif %}
<hr>
&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'publisher:index' %}">home</a>
{% endblock %}

publisher/templates/publisher/index.html
{% extends 'publisher/base.html' %}

{%block main %}

<p style="font-size:22px;" align="center">
	Here are the latest posts of problems sorted by date published.<br/> 
	Click on the problem headline to solve it, then view the statistics. <br/>
	Problem Type: Multiple Choice (MC) or Filling in Blank (FB) </br>
	Problem Level: 1 to 5 (simple to Olympic) 
</p>
	<hr/>
<p style="font-size:24px;" align="center">
	(to contribute a problem, please login first)<br/>
	<a style="color:#57B6B4" href="{%url 'publisher:create_mc_problem' %}">create a multi-choice problem</a> |
	<a style="color:#57B6B4" href="{%url 'publisher:create_fb_problem' %}">create a fill-in-blank problem</a>|
	<a style="color:#57B6B4" href="{%url 'publisher:rest' %}">rest_webservice</a> 
</p>

	{%if headers %}
		<table style="font-size:20px;" align="center" style="border:0;">
		<tr><th width="50px;"></th>
			<th width="240px;" align="left">Headline</th>
			<th width="220px;" align="left">Level/Type/Subject</th>
			<th width="160px;">Post Date</th>
			<th width="60px;">👍</th>
			<th width="60px;">👎</th>
	    </tr>
		{%for header in headers %}
		<tr>
			<th>{{forloop.counter}}</th>
			<td style="font-size:22px;" align="left">
				<a style="color:#57B6B4;" href="{% url 'publisher:detail' header.0 %}">{{header.1}}</a>
			</td>
			<td align="left">{{header.4}}-{{header.2}}-{{header.3}}</td>
			<td>{{header.5|date:'y-m-d H:i'}}</td>
			<td align="center">{{header.6}}</td>
			<td align="center">{{header.7}}</td>
		</tr>
		{%endfor%}
		</table>
	{% else %}
		<p>Sorry! There are no posts avaiable</p>
	{% endif %}

{%endblock%}

publisher/templates/publisher/login.html
{% extends 'publisher/base.html' %}

{%block main%}
<form method="post">
	{% csrf_token %}
	{{form.as_p}}
	<input type="submit" value="login">
	
</form>
{%endblock%}

publisher/templates/publisher/name.html
{% extends 'publisher/base.html' %}

{%block main %}

<form action="{% url 'publisher:name' %}" method="post">

	{% csrf_token %}

	{{ form }}

	<input type="submit" value="Submit">
</form>

{%endblock%}

publisher/templates/publisher/signup.html
{% extends 'publisher/base.html'%}

{%block main %}

  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
	<table>
    {{ form }}
	</table>
    <button type="submit">Sign up</button>
  </form>
{%endblock%}

publisher/templates/publisher/statistics.html
{% extends 'publisher/base.html' %}

{% block main %}
	<h3>Topic. {{ problem.headline }}</h3>
	<p><b>Question.</b> {{ problem.text }}</p>
	<hr/>
	<p><b>Statistics</b></p>
	<table>
	<tr><th style="min-width:160px;">Correct</th> <th style="width:160px;">Head Count</th></tr>
	<tr><th> &#x2705; </th><td align="center">{{problem.num_correct}} </td></tr>
	<tr><th> &#x274E; </th><td align="center">{{problem.num_wrong  }} </td></tr>
	</table>
	<hr/>
	{% if problem.prob_type == "选择" %}
	<p><b>Details</b></p>
		<table>
		<tr><th style="min-width:160px;">Choice</th> <th style="width:160px;">Head Count</th></tr>
		{% for choice in problem.choice_set.all %}
			<tr><th>({{forloop.counter}}).&nbsp; {{choice.choice_text}}</th><th>{{choice.votes}}</th></tr>
		{% endfor %}
		</table>
	{% endif %}
	<hr/>
	<h3>Your Opinion?</h3>
	<form action="{% url 'publisher:vote' problem.id %}" method="post">
		{% csrf_token %}
		<input type="radio" name="vote" id="vote-pos" value="pos"><label for="vote-pos">Like</label> &nbsp;&nbsp;	
		<input type="radio" name="vote" id="vote-neg" value="neg"><label for="vote-neg">Dislike</label> 	
		<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;
		<input type="submit" name="submit" value="vote!">
	</form>
	<hr>
	&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'publisher:index' %}">home</a>
{% endblock %}